services:
  - type: web
    name: backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: node dist/app/server.js
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: PORT
        value: 5000
